# -*- coding: utf-8 -*-
"""habit tracker 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hk6LK4dNNGFX-IEV4pFXDC-bIY8W-dix
"""

import random

habits = []
progress = []
name=str(input("Enter your name: "))

quotes = [
    "Keep going — progress, not perfection!",
    "Small steps every day lead to big changes.",
    "Don’t wish for it, work for it!",
    "Your future self will thank you.",
    "Discipline is doing what needs to be done, even when you don’t feel like it."
]

while True:
    print("\n=== MAIN MENU ===")
    print("1. Manage habits")
    print("2. Log your habits")
    print("3. View progress")
    print("4. Motivation message")
    print("5. Reset tracker")
    print("0. Exit")

    choice = input("Enter your choice: ")


    if choice == "1":
        print(name, "You choose option one (Manage Habits)")
        sub_choice = ""
        while sub_choice != "0":
            print("\n=== SUB MENU ===")
            print("1. Add a habit")
            print("2. Remove a habit")
            print("0. Back to Main Menu")
            sub_choice = input("Enter your sub-choice: ")

            if sub_choice == "1":
                print("You choose option one (Add a habit)")
                new_habit = input("Enter the name of the habit: ")
                if new_habit in habits:
                    print("Habit already exists")
                else:
                    habits.append(new_habit)
                    progress.append(0)
                    print(f"The habit '{new_habit}' added!")

            elif sub_choice == "2":
                print("You choose option two (Remove a habit)")
                if not habits:
                    print("You have no habits to remove.")
                else:
                    print("\nYour current habits:")
                    for i in range(len(habits)):
                        print(f"{i + 1}. {habits[i]}")
                    try:
                        remove_index = int(input("Enter the number of the habit to remove: ")) - 1
                        if 0 <= remove_index < len(habits):
                            print(f"Habit '{habits[remove_index]}' removed.")
                            habits.pop(remove_index)
                            progress.pop(remove_index)
                        else:
                            print("Invalid number. Try again.")
                    except ValueError:
                        print("Please enter a valid number.")

            elif sub_choice == "0":
                print("Exiting Sub-menu.")
            else:
                print("Invalid sub-menu choice. Please try again.")

    elif choice == "2":
        if not habits:
            print("You have no habits to log. Add one first!")
        else:
            for i in range(len(habits)):
                done = input(f"Did you complete '{habits[i]}' today? (y/n): ").lower()
                if done == "y":
                    progress[i] +=1
                    print("Nice! Progress saved.")


                else:
                    print("No problem — try again tomorrow!")

    elif choice == "3":
        if not habits:
            print("You have no habits to view.")
        else:
            print("\n--- Progress Report ---")
            for i in range(len(habits)):
                print(f"{habits[i]}: completed {progress[i]} time(s)")
                percent = (progress[i] / 7) * 100
                print(f"{habits[i]}: {percent:.1f}% completion this week")

    elif choice == "4":
        print("\n--- Motivation Message ---")
        print(random.choice(quotes))

    elif choice == "5":
        confirm = input(f"{name}, are you sure you want to reset everything? (yes/no): ").lower()
        if confirm == "yes":
            habits.clear()
            progress.clear()
            print("All data has been reset!")
        else:
            print("Reset canceled.")

    elif choice == "0":
        print(f"Goodbye {name}! Keep building great habits!")
        break

    else:
        print("Invalid choice. Please try again.")

